In [5]:
import numpy as np
D=np.array([10,20,30])
T=np.array([2,3,4])
s=D/T
s


array([5.        , 6.66666667, 7.5       ])

In [12]:
l=[[1,2,3],[2,3,4],[3,4,5]]
arr=np.array(l)
arr

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [13]:
arr[2][1]                           #indexing in array

4

In [14]:
arr[2][2]

5

In [15]:
arr.ndim

2

In [16]:
arr.shape

(3, 3)

In [17]:
arr.shape[0]            

3

In [18]:
arr.size

9

In [19]:
arr.dtype

dtype('int32')

In [21]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
a+b


array([ 6,  8, 10, 12])

In [22]:
2*(a+b)

array([12, 16, 20, 24])

In [3]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
arr*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [6]:
arr[1][1]=50                         #mutualibity
arr

array([[ 1,  2,  3],
       [ 4, 50,  6],
       [ 7,  8,  9]])

In [7]:
arr = np.array(arr,dtype=float)      #change into float
arr

array([[ 1.,  2.,  3.],
       [ 4., 50.,  6.],
       [ 7.,  8.,  9.]])

In [18]:
arr =np.array([[1,2,3,50,60],[20,60,40,45,55]])
arr

array([[ 1,  2,  3, 50, 60],
       [20, 60, 40, 45, 55]])

In [19]:
pas=50

In [20]:
arr>pas

array([[False, False, False, False,  True],
       [False,  True, False, False,  True]])

In [21]:
arr[arr>pas]

array([60, 60, 55])

In [24]:
c1=np.array([20,40,60])
c2=np.array([10,80,90])
c=c1+c2
c

array([ 30, 120, 150])

In [26]:
c[c>30]

array([120, 150])

In [31]:
st=np.array([["delhi","mumbai","pune","goa"],["jk","uttarakhand","harayana","punjab"]])
st

array([['delhi', 'mumbai', 'pune', 'goa'],
       ['jk', 'uttarakhand', 'harayana', 'punjab']], dtype='<U11')

In [32]:
st[0:2,1:3]

array([['mumbai', 'pune'],
       ['uttarakhand', 'harayana']], dtype='<U11')

In [34]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
a=arr[0:2,0:2]
a

array([[1, 2],
       [4, 5]])

In [48]:
a[a%3==0]

array([], dtype=int32)

In [2]:
import numpy as np
a1=np.array([[2,4,5,6],[45,90,78,45]])

In [3]:
a1

array([[ 2,  4,  5,  6],
       [45, 90, 78, 45]])

In [6]:
a1

array([[ 2,  4,  5,  6],
       [45, 90, 78, 45]])

In [7]:
for i in a1:
    print(i)

[2 4 5 6]
[45 90 78 45]
