In [1]:
import numpy as np
a1=np.array([[2,4,5,6],[45,90,78,45]])

In [2]:
a1

array([[ 2,  4,  5,  6],
       [45, 90, 78, 45]])

In [4]:
for i in a1:
    print(i)

[2 4 5 6]
[45 90 78 45]


In [5]:
a=np.array([[[1,2,3,4,5,6]]])
a[0][0][0]

1

In [ ]:
#$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$4

UNIVERSAL FUNCTIONS:                                              

In [3]:
import numpy as np
a=np.array([1,4,9,16,25,36,49,64,81,100])
a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [4]:
np.sin(a)

array([ 0.84147098, -0.7568025 ,  0.41211849, -0.28790332, -0.13235175,
       -0.99177885, -0.95375265,  0.92002604, -0.62988799, -0.50636564])

In [5]:
np.sqrt(a)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [6]:
np.cos(a)

array([ 0.54030231, -0.65364362, -0.91113026, -0.95765948,  0.99120281,
       -0.12796369,  0.30059254,  0.39185723,  0.77668598,  0.86231887])

In [7]:
np.tan(a)

array([ 1.55740772,  1.15782128, -0.45231566,  0.30063224, -0.13352641,
        7.75047091, -3.17290855,  2.34786031, -0.81099442, -0.58721392])

In [9]:
np.exp(a)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06,
       7.20048993e+10, 4.31123155e+15, 1.90734657e+21, 6.23514908e+27,
       1.50609731e+35, 2.68811714e+43])

In [11]:
from numpy import pi

In [14]:
np.sin(pi/2)

1.0

In [15]:
a=np.array([12.45,3.23,15.67,-9.17])
np.floor(a)

array([ 12.,   3.,  15., -10.])

In [17]:
a=np.array([12.45,3.23,15.67,-9.17])
np.ceil(a)

array([13.,  4., 16., -9.])

In [18]:
arr=np.array([1,2,3,4,5,6,7,8,9])
np.reshape(arr,(3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
np.reshape(arr,(1,9))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [20]:
np.resize(arr,(3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.ravel(a)

array([12.45,  3.23, 15.67, -9.17])

In [23]:
a

array([12.45,  3.23, 15.67, -9.17])

In [24]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
np.ravel(a)

array([1, 2, 3, 4, 5, 6])

In [29]:
c=lambda a,b:a+b
c(10,20)

30

In [34]:
c=lambda c:(9/5)*c+32
c(0)

32.0

In [32]:
c=lambda a,b:a**b
c(2,2)

4

In [35]:
np.fromfunction(lambda x,y:x+y,(4,4))

array([[0., 1., 2., 3.],
       [1., 2., 3., 4.],
       [2., 3., 4., 5.],
       [3., 4., 5., 6.]])

In [36]:
np.fromiter([1,2,3,4,5],dtype=int)

array([1, 2, 3, 4, 5])

In [37]:
np.fromstring("1 2 3 4 5 6 7 8 9",sep=" ",dtype=int)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [40]:
b=np.ones((3,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [43]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
np.eye(3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [49]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
np.diag(arr)

array([1, 5, 9])

In [52]:
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [53]:
np.tri(3,k=1)

array([[1., 1., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [54]:
np.tril(arr)                     

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [57]:
np.triu(arr)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [58]:
np.triu(arr,k=1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0]])

In [59]:
np.diagflat([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [60]:
np.diagflat([1,2,3],k=1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])