In [10]:
import numpy as np
l=np.array([[1,2,3,4],[5,6,7,8],[2,3,4,5],[4,5,7,8]])
l

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [2, 3, 4, 5],
       [4, 5, 7, 8]])

In [6]:
np.arange(1,22.5,1.1)       #like range but in float

array([ 1. ,  2.1,  3.2,  4.3,  5.4,  6.5,  7.6,  8.7,  9.8, 10.9, 12. ,
       13.1, 14.2, 15.3, 16.4, 17.5, 18.6, 19.7, 20.8, 21.9])

In [8]:
np.linspace(1,5,4)          #no. between 1 to 5 , how many no. we need = 4

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [11]:
l

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [2, 3, 4, 5],
       [4, 5, 7, 8]])

In [12]:
np.trace(l)                #sum of diagonal elements

19

In [15]:
from numpy import random
a=np.random.rand(2,1)           #print array of 2x1 ,only between 0 to 1
a

array([[0.63857876],
       [0.50754707]])

In [17]:
b=np.random.randint(1,400,(3,3))   #print integers
b

array([[ 79,  64,  61],
       [ 36, 210, 102],
       [  3, 386, 120]])

In [23]:
c=np.random.randn(5,10)
c

array([[-0.89707446,  0.04420052, -0.87488434, -0.28192597, -0.49459319,
         0.3449507 ,  0.78816435, -0.25435419, -2.04996096,  0.21967519],
       [-0.58094982, -0.8868724 ,  1.02952344,  0.02082969,  0.41298441,
         0.53922506,  0.11794581,  2.16378317,  1.80147822, -0.14650497],
       [ 1.0864374 ,  0.20266423,  1.72795573, -0.40002568,  1.14334708,
        -0.5962503 , -0.29772792, -0.67396866, -0.92139823, -0.52507903],
       [ 0.36168827, -0.50348788,  0.30466463,  0.34452598,  1.29129158,
        -0.69499764, -0.0229185 , -0.72007887,  1.4057844 , -1.58987341],
       [ 1.26832401, -0.188873  , -1.04138176, -0.40641556,  1.7559484 ,
        -0.49714405, -0.15057142, -0.55780037, -0.33581468,  0.8820256 ]])

In [24]:
l

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [2, 3, 4, 5],
       [4, 5, 7, 8]])

In [26]:
l.sort()
l

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [2, 3, 4, 5],
       [4, 5, 7, 8]])

In [27]:
l.max()

8

In [29]:
c=np.array([[1,12],[6,2]])
c


array([[ 1, 12],
       [ 6,  2]])

In [30]:
np.argmax(c,axis=0)

array([1, 0], dtype=int64)

In [32]:
np.cumsum([1,2,3,4,5,6])

array([ 1,  3,  6, 10, 15, 21], dtype=int32)